import { useCallback } from "react";

import RibbonButton from "./RibbonButton";
import RibbonGroup from "./RibbonGroup";
import { cubeIcon, exportIcon } from "./icons";
import { useToastStore } from "../../store/toastStore";
import { useModellerStore } from "../modeller/modellerStore";
import { isTauri } from "../../lib/backend";

/**
 * IFC ribbon tab. Verzamelt IFC-import/export acties op één plek
 * (eerder verspreid over Modeller-ribbon onder "Invoegen"). De page
 * `/ifc` toont status van de huidige import (aantal rooms/wall types/etc).
 */
export default function IfcTab() {
  const addToast = useToastStore((s) => s.addToast);
  const importModel = useModellerStore((s) => s.importModel);

  const handleImportIfc = useCallback(async () => {
    if (!isTauri()) {
      addToast(
        "IFC-import via sidecar werkt alleen in de desktop-app.",
        "info",
      );
      return;
    }
    try {
      const { invoke } = await import("@tauri-apps/api/core");
      addToast("IFC-bestand wordt verwerkt...", "info");
      const data = await invoke<{
        rooms: Array<{
          name: string;
          function: string;
          polygon: Array<{ x: number; y: number }>;
          floor: number;
          height: number;
        }>;
      }>("import_ifc", { filePath: "" });
      // Map sidecar rooms into ModelRoom shape (id auto-generated by store).
      const rooms = data.rooms.map((r, i) => ({
        id: `ifc-${i}`,
        name: r.name,
        function: r.function,
        polygon: r.polygon,
        floor: r.floor,
        height: r.height,
      }));
      importModel(rooms);
      addToast(`${rooms.length} ruimten geïmporteerd uit IFC`, "success");
    } catch (err) {
      const msg = err instanceof Error ? err.message : String(err);
      addToast(`IFC-import mislukt: ${msg}`, "error");
    }
  }, [addToast, importModel]);

  return (
    <>
      <RibbonGroup label="Invoegen">
        <RibbonButton
          icon={cubeIcon}
          label="Importeer IFC"
          onClick={handleImportIfc}
        />
      </RibbonGroup>

      <RibbonGroup label="Exporteren">
        <RibbonButton
          icon={exportIcon}
          label="Export IFCX"
          onClick={() => {
            // Modeller-tab heeft al een IFCX-export — duplicaat hier zou
            // refactor van _handleExportIfc vereisen. Voor nu: redirect-tip.
            addToast(
              "IFCX export staat in de Modeller-tab onder Invoegen.",
              "info",
            );
          }}
        />
      </RibbonGroup>
    </>
  );
}
